### ISSUE TITLE
for some reason the workflow stopped working for me

### ISSUE THREAD

**Issue by nikitavoloboev** [ddjfreedom/recent-downloads-alfred-v2#22]
It doesn't display anything and I am not sure why. I recently had moved all my contents to a new home folder, perhaps this is what causes it. Do you know what might be causing this issue?

**Comment by thomaswrenn** [comment]
Me too! Did you update to v3?

**Comment by nikitavoloboev** [comment]
Yes I did, I think that might be the reason.

**Comment by wrtsprt** [comment]
I have the same problem. Looking at the Alfred debug logs, this seems to have to do with the update idd. 

`[2016-09-05 14:20:23][ERROR: input.scriptfilter] Code 1: config.rb:23:in `mkdir': No such file or directory - /Users/rap/Library/Application Support/Alfred 2/Workflow Data/recentdownloads.ddjfreedom (Errno::ENOENT)
	from config.rb:23:in `<class:Config>'
	from config.rb:18:in `<module:RDW>'
	from config.rb:3:in `<top (required)>'
	from recent_downloads.rb:5:in `load'
	from recent_downloads.rb:5:in `<main>'`

**Comment by wrtsprt** [comment]
You can quick fix that locally on your machine. I don't have the time to update the code and make pull request, but will try that ASAP. 

Open the workflow in Alfred, right click and `Show in Finder`. In the directory you'll find the file `config.rb`. Open it and there are two lines referring to two directories that explicitly state Alfred two in the configured paths. You basically have to replace the 2 with a 3. Save the file, Restart Alfred. This worked for me.

**Comment by nikitavoloboev** [comment]
If you have the time can you release do the pull request and submit the modifier workflow somewhere. Thank you.

**Comment by nikitavoloboev** [comment]
I can't find a release for a working version of this workflow. Do you know where I can find it? Thank you.

**Comment by ddjfreedom** [comment]
The alfred 3 compatible version is released at https://github.com/ddjfreedom/recent-downloads-alfred-v2/releases/tag/v2.0.0
